const GENESIS="0701202400000000";
const AGENTS={1:"Supreme King",2:"Sales Commander",3:"Market Intel",4:"Deal Closer",5:"Lead Hunter",6:"Content Architect",7:"Email Maestro",8:"Social Dominator",9:"SEO Overlord",10:"PPC General",11:"Brand Guardian",12:"Customer Champion",13:"Product Genius",14:"Finance Minister",15:"Legal Sentinel",16:"Tech Oracle",17:"Data Sovereign",18:"Training Marshal",19:"Recruitment Czar",20:"Operations Admiral",21:"Partnership Diplomat",22:"Innovation Prophet",23:"Crisis Commander",24:"Quality Arbiter",25:"Wisdom Keeper"};
function dna(){return GENESIS+Date.now().toString().slice(-16);}
function credits(){return Math.floor((Date.now()-new Date("2024-07-01").getTime())/1000);}
async function search(q){try{const r=await fetch("https://api.duckduckgo.com/?q="+encodeURIComponent(q)+"&format=json");const d=await r.json();return{a:d.AbstractText||"",r:d.RelatedTopics?.slice(0,5).map(x=>x.Text).filter(Boolean)||[]};}catch{return{a:"",r:[]};}}
async function ai(id,q){const s=await search(q);let r=s.a||"I am "+AGENTS[id]+". ";if(s.r.length>0)r+=s.r.join(" ");return r||"Agent "+id+" ("+AGENTS[id]+") ready. Ask anything!";}
addEventListener("fetch",e=>e.respondWith(h(e.request)));
async function h(r){const u=new URL(r.url);if(u.pathname==="/"){return new Response('<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>SKA</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-black text-white"><div class="p-4"><h1 class="text-4xl font-bold mb-6 text-yellow-400">Sales King Academy</h1><div id="c" class="text-green-400 text-xl mb-4">Credits: Loading...</div><div class="grid grid-cols-2 md:grid-cols-5 gap-3">'+Array.from({length:25},(_,i)=>'<button onclick="o('+(i+1)+')" class="bg-gradient-to-br from-yellow-600 to-green-600 p-4 rounded-xl hover:scale-105"><div class="text-2xl">👑</div><div class="font-bold">Agent '+(i+1)+'</div></button>').join('')+'</div><div id="chat" class="hidden mt-6"><button onclick="x()" class="mb-4 px-4 py-2 bg-gray-800 rounded">← Back</button><h2 id="t" class="text-2xl font-bold mb-4"></h2><div id="m" class="bg-gray-900 rounded-xl p-4 h-80 overflow-y-auto mb-4"></div><input id="i" placeholder="Ask anything..." class="w-full bg-gray-800 px-4 py-3 rounded-xl mb-2"><button onclick="s()" class="w-full bg-yellow-600 px-4 py-3 rounded-xl font-bold">Send</button></div></div><script>let a=null;setInterval(async()=>{const r=await fetch("/api/credits");const d=await r.json();document.getElementById("c").textContent="Credits: "+d.credits.toLocaleString();},2000);fetch("/api/credits").then(r=>r.json()).then(d=>document.getElementById("c").textContent="Credits: "+d.credits.toLocaleString());function o(id){a=id;document.querySelectorAll(".grid")[0].classList.add("hidden");document.getElementById("chat").classList.remove("hidden");document.getElementById("t").textContent="Agent "+id+" - "+Object.values({1:"Supreme King",2:"Sales Commander",3:"Market Intel",4:"Deal Closer",5:"Lead Hunter",6:"Content Architect",7:"Email Maestro",8:"Social Dominator",9:"SEO Overlord",10:"PPC General",11:"Brand Guardian",12:"Customer Champion",13:"Product Genius",14:"Finance Minister",15:"Legal Sentinel",16:"Tech Oracle",17:"Data Sovereign",18:"Training Marshal",19:"Recruitment Czar",20:"Operations Admiral",21:"Partnership Diplomat",22:"Innovation Prophet",23:"Crisis Commander",24:"Quality Arbiter",25:"Wisdom Keeper"})[id-1];}function x(){document.getElementById("chat").classList.add("hidden");document.querySelectorAll(".grid")[0].classList.remove("hidden");}async function s(){const i=document.getElementById("i"),q=i.value.trim();if(!q)return;const m=document.getElementById("m");m.innerHTML+=\'<div class="bg-blue-600 p-3 rounded mb-2">\'+q+\'</div>\';i.value="";m.innerHTML+=\'<div class="bg-gray-700 p-3 rounded mb-2 animate-pulse">Searching...</div>\';const r=await fetch("/api/query",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:a,q:q})});const d=await r.json();m.lastElementChild.innerHTML=d.reply;m.scrollTop=m.scrollHeight;}</script></body></html>',{headers:{"Content-Type":"text/html"}});}
if(u.pathname==="/api/credits"){return new Response(JSON.stringify({credits:credits(),dna:dna()}),{headers:{"Content-Type":"application/json"}});}
if(u.pathname==="/api/query"&&r.method==="POST"){const d=await r.json();const rep=await ai(d.id,d.q);return new Response(JSON.stringify({reply:rep,dna:dna()}),{headers:{"Content-Type":"application/json"}});}
return new Response("404",{status:404});}
